services:
  myapi:
    image: myapi
    ports:
      - "8000:8080"
    env_file:
      - app/data/private/.env
    volumes:
      - ./app/data:/home/noboobs/n/app/data
      - /home/noboobs/noBS_BotIntegrator/src:/home/noboobs/n/app/data/images